name: timetracker_app
description: Timetracker

publish_to: "none"
version: 0.0.1+x

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0
  cupertino_icons: ^1.0.3
  easy_localization: ^3.0.0
  flutter_secure_storage: ^4.2.0
  get_it: ^7.1.3
  http: ^0.13.3
  intl: ^0.17.0
  modal_bottom_sheet: ^2.0.0
  provider: ^5.0.0
  streaming_shared_preferences: ^2.0.0
  flutter_screenutil: ^5.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/mogic-logo.png
    - assets/translations/
